### PR TITLE
Updated packages 

### PR DESCRIPTION
**Pull request by gabog**
In this PR:

- Updated BF packages to 4.11
- Consolidated AdaptiveCards packages to 2..2

### CODE REVIEW

**Review by Virtual-Josh — APPROVED** [review]

**Review by ceciliaavila — APPROVED** [review]

**Review by mrivera-ms — COMMENTED** [review]
Should we update this to 4.11.1?

**Comment by gabog** [comment]
@mrivera-ms 4.11.1 shows on myget but not on nuget (I was just targetting released versions), is 4.11.1 out?

**Comment by mrivera-ms** [comment]
> @mrivera-ms Monica Rivera FTE 4.11.1 shows on myget but not on nuget (I was just targetting released versions), is 4.11.1 out?

It is scheduled to be out on 11/17.

**Comment by gabog** [comment]
Ah, OK, updated them to use 4.11.1

**Review by mrivera-ms — APPROVED** [review]

**Pull request merged**
