### PR TITLE
JS skill echobot -> Cloud Adapter

### PR DESCRIPTION
**Pull request by joshgummersall**
This PR migrates the Skill Echo Bot to Cloud Adapter. I will migrate the other bots in subsequent PRs.

Note: much of the diff has to do with running code formatting in VSCode.

### CODE REVIEW

**Review by stevengum — APPROVED** [review]
LGTM, especially around the AuthenticationConfiguration changes!

But why the shift from `'` to `"`?

**Comment by joshgummersall** [comment]
@stevengum, I added the `.prettierrc` from `botbuilder-js`. Should be better now!

**Review by stevengum — APPROVED** [review]
Thanks for running the linting script!

**Review by mdrichardson — APPROVED** [review]
LGTM

**Review by gabog — APPROVED** [review]

**Pull request merged**
